[package]
name = "mil_std_1553b_sim"
authors = ["Michael House <mjhouse@protonmail.com>"]
version = "0.1.0"
edition = "2021"
build = "src/build.rs"

[dependencies]
slint = "0.3.0"

[build-dependencies]
slint-build = "0.3.0"